import type { RadarReplayQualityResponse } from '@/types/radar';

const replayQualityResponse = {
  schemaVersion: 'radar-replay-quality-v1',
  checkedAt: '2026-09-01T04:00:00Z',
  state: 'not_ready',
  quality: 'partial',
  engineeringState: 'complete',
  validationState: 'collecting',
  shadowCollectionAllowed: true,
  stage9QualityGatePassed: false,
  replayRunId: 'replay-20260803-1430',
  createdAt: '2026-09-01T03:59:00Z',
  evidenceSha256: 'a'.repeat(64),
  sampleCounts: {
    development: 10,
    calibration: 5,
    holdout: 3,
  },
  includedCount: 12,
  excludedCount: 6,
  scopedExclusionCount: 118,
  scopedExclusionCounts: {
    industry: 115,
    corporate_action: 3,
  },
  missingCount: 4,
  unverifiableCount: 2,
  failedCount: 0,
  futureViolationCount: 0,
  duplicateStateViolationCount: 0,
  multiStateViolationCount: 0,
  labelCounts: {
    market: 3,
    sector: 3,
    etf: 3,
    leader: 3,
  },
  outputCounts: {
    market: 3,
    sector: 3,
    etf: 3,
    leader: 3,
  },
  etfReadinessCounts: {
    formalAdmissionCount: 3,
    monitoringReadyCount: 1,
    monitoringMissingCount: 2,
    rankingPolicyReadyCount: 0,
    rankingPolicyMissingCount: 3,
  },
  comparableLabelCount: 12,
  incomparableLabelCount: 0,
  disputedLabelCount: 0,
  unverifiableLabelCount: 0,
  unlabeledOutputTargetCount: 2,
  unlabeledOutputTargetCounts: {
    market: 0,
    sector: 1,
    etf: 0,
    leader: 1,
  },
  partitionChronologyValid: false,
  missingDomains: ['corporate_action'],
  missingPartitions: ['holdout'],
  missingLabelDomains: ['leader'],
  missingOutputDomains: ['leader'],
  unverifiableOutputDomains: [],
  failedOutputDomains: [],
  readyOutputDomains: ['market', 'sector', 'etf'],
  missingLabelPartitions: ['holdout'],
  reasonCodes: ['replay_required_domain_missing'],
  metrics: {
    market: null,
    sector: null,
    etf: null,
    leader: null,
  },
} satisfies RadarReplayQualityResponse;

void replayQualityResponse;
