import type { RadarReplayEtfResearchResponse } from '../src/types/radar';

export const etfResearchContract = {
  schemaVersion: 'radar-replay-etf-research-v1',
  checkedAt: '2026-09-07T15:00:00+08:00',
  state: 'available',
  quality: 'partial',
  evidenceSha256: 'a'.repeat(64),
  snapshot: {
    schemaVersion: 'radar-replay-etf-research-v1',
    replayOutputBundleId: 'bundle-1',
    sampleId: 'sample-1',
    radarRunId: 'run-1',
    asOf: '2026-09-07T14:45:00+08:00',
    createdAt: '2026-09-07T14:46:00+08:00',
    source: '交易所官方ETF产品分类研究输出',
    sourceTime: '2026-09-07T14:45:00+08:00',
    fetchedAt: '2026-09-07T14:45:00+08:00',
    outputSnapshotSha256: 'b'.repeat(64),
    sourceSnapshotSha256: 'c'.repeat(64),
    classificationMappingVersion: 'classification-v1',
    productCount: 1,
    indexResearchReadyCount: 1,
    activeSeparateTrackCount: 0,
    outOfScopeAssetCount: 0,
    evidenceIncompleteCount: 0,
    formalAdmissionAvailable: true,
    formalAdmissionCount: 1,
    monitoringReadyCount: 1,
    monitoringMissingCount: 0,
    rankingPolicyReadyCount: 0,
    rankingPolicyMissingCount: 1,
    researchOnly: true,
    rankingReady: false,
    formalUsable: false,
    stateTransitionAllowed: false,
    items: [{
      symbol: '510300',
      researchState: 'product_ready_for_index_research',
      targetIndexName: '沪深300指数',
      monitoringStatus: 'ready',
      rankingStatus: 'missing',
      monitoringReasons: [],
      rankingReasons: ['etf_rule_not_frozen'],
    }],
    reasonCodes: [],
  },
  reasonCodes: [],
} satisfies RadarReplayEtfResearchResponse;
